name: projectlight
description: A app with dating and marriage in mind

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  path_provider: ^1.6.7
  connectivity: ^0.4.8+5
  camera: ^0.5.7+4
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.11
  firebase_storage: ^3.1.5
  firebase_database: ^3.1.5
  google_fonts: ^1.1.0
  email_validator: ^1.0.4
  modal_progress_hud: ^0.1.3
  flutter_form_builder: ^3.9.0


dev_dependencies:
  logger: ^0.9.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/